"""Reproduce Python/C++/Rust HQ resampling parity and Kotlin reference assets.

Run with conda MIR. Sources and reference values are deterministic; models are
not involved, so a failed test cannot be masked by a neural output tolerance.
"""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import tempfile
import numpy as np
import soxr

RATES = [(8000,22050),(16000,22050),(22050,16000),(22050,32000),
         (32000,22050),(44100,16000),(44100,22050),(48000,16000),
         (48000,22050),(48000,44100),(96000,22050),(16000,16000)]
CHUNKS = (0,1,17,441,2048,32769)

def digest(data): return hashlib.sha256(data).hexdigest()

def cases():
    for source,target in RATES:
        t=np.arange(source+17)/source
        rng=np.random.default_rng(20260905+source)
        x=(0.1*np.sin(2*np.pi*317*t)+0.2*np.sin(2*np.pi*(source*.41)*t)
           +rng.normal(0,0.05,len(t))).astype(np.float32)
        x[:3]=[0,1,-1]
        reference=soxr.ResampleStream(source,target,1,dtype='float32',quality='HQ')
        output=[];counts=[];position=0;index=0
        while position<len(x):
            count=min(CHUNKS[index%len(CHUNKS)],len(x)-position)
            block=reference.resample_chunk(x[position:position+count])
            output.extend(block);counts.append(len(block))
            index+=1;position+=count
        block=reference.resample_chunk(np.empty(0,np.float32),last=True)
        output.extend(block);counts.append(len(block))
        yield source,target,x,np.asarray(output,np.float32),counts

def main():
    parser=argparse.ArgumentParser()
    parser.add_argument('--write-golden',type=Path)
    parser.add_argument('--cpp-replay',type=Path)
    parser.add_argument('--rust-replay',type=Path)
    parser.add_argument('--library',type=Path)
    parser.add_argument('--output',type=Path)
    args=parser.parse_args()
    if not (args.write_golden or args.cpp_replay or args.rust_replay):parser.error('select validation or golden generation')
    if args.rust_replay and not args.library:parser.error('--rust-replay requires --library')
    records=[];rows=[]
    if args.write_golden:args.write_golden.mkdir(parents=True,exist_ok=True)
    for source,target,x,expected,counts in cases():
        name=f'{source}-{target}'
        if args.write_golden:
            incoming=x.astype('<f4').tobytes();reference=expected.astype('<f4').tobytes()
            (args.write_golden/f'{source}-input.f32').write_bytes(incoming)
            (args.write_golden/f'{name}-output.f32').write_bytes(reference)
            rows.append('\t'.join([str(source),str(target),digest(incoming),digest(reference),','.join(map(str,counts))]))
        with tempfile.TemporaryDirectory() as tmp:
            temp=Path(tmp);x.tofile(temp/'input.f32')
            for language,exe in [('cpp',args.cpp_replay),('rust',args.rust_replay)]:
                if exe is None:continue
                for chunk in (1,441,1000,len(x)):
                    command=[str(exe.resolve())]
                    if language=='rust':command.append(str(args.library.resolve()))
                    command.extend(map(str,[source,target,chunk,temp/'input.f32',temp/'output.f32']))
                    subprocess.run(command,check=True,capture_output=True)
                    actual=np.fromfile(temp/'output.f32',dtype='<f4')
                    np.testing.assert_allclose(actual,expected,rtol=0,atol=2e-6)
                    records.append(dict(language=language,source_rate=source,target_rate=target,chunk=chunk,
                        samples=len(actual),max_abs_error=float(np.max(np.abs(actual-expected)))))
    if args.write_golden:
        (args.write_golden/'manifest.tsv').write_text('\n'.join(rows)+'\n')
        (args.write_golden/'README.txt').write_text('Generated by mir-core/native-dsp/tools/resampling_parity.py.\n'
            'Reference: Python-SoXR 0.5.0.post1, libsoxr 0.1.3-11-gedbdb40, HQ mono float32.\n'
            'Columns: source rate, target rate, input SHA256, output SHA256, per-chunk output counts.\n'
            'Chunk sizes cycle through 0,1,17,441,2048,32769; final empty chunk drains the filter.\n')
    report={'passed':True,'atol':2e-6,'rtol':0,'comparisons':records}
    if args.output:args.output.write_text(json.dumps(report,indent=2)+'\n')
    print(f'{len(records)} native comparisons passed; max absolute error '+str(max((r['max_abs_error'] for r in records),default=0)))

if __name__=='__main__':main()
